[build-system]
requires = ["setuptools>=42", "wheel", "scikit-fuzzy", "codecarbon"]
build-backend = "setuptools.build_meta"

[project]
name = "frugalityscore"
version = "0.1"
dependencies = ["requests", "scikit-fuzzy", "codecarbon"]